configurations:
  - sources:
      - Domain/Sources/Entities/
      - DesignSystem/Sources/DesignSystem/Components/TypesView.swift
    templates:
      - Templates/Pokemon.Type+preview.stencil
    output: DesignSystem/Sources/DesignSystem/Components/TypesView.swift
  - sources:
      - Domain/Sources/Entities/
    templates:
      - Templates/Entity+stub.stencil
    output: Core/Sources/Core/Generated/Entity+stub.swift
