configurations:
  - sources:
      - Domain/Sources/Entities/
      - DesignSystem/Sources/DesignSystem/Components/TypesView.swift
    templates:
      - Templates/Pokemon.Type+preview.stencil
    output: DesignSystem/Sources/DesignSystem/Components/TypesView.swift
  - sources:
      - Domain/Sources/Entities/
    templates:
      - Templates/Entity+stub.stencil
    output: Core/Sources/Core/Generated/Entity+stub.swift
  - sources:
      - Domain/Sources/Repositories/
    templates:
      - Templates/AutoMockable.stencil
    args:
      autoMockableImports:
        - Repository
        - Entity
    output: Domain/Tests/DomainTests/Generated/RepositoryMock.swift
  - sources:
      - Domain/Sources/UseCases/
    templates:
      - Templates/AutoMockable.stencil
    output: Feature/Tests/FeatureTests/Generated/UseCaseMock.swift 
