// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Pokedex",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "Pokedex",
            targets: ["AppModule"],
            bundleIdentifier: "com.hicka04.Pokedex",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
        .iOSApplication(
            name: "PokemonListSandbox",
            targets: ["SandboxPokemonListModule"],
            bundleIdentifier: "com.hicka04.Pokedex.Sandbox.PokemonList",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
        .iOSApplication(
            name: "PokemonDetailSandbox",
            targets: ["SandboxPokemonDetailModule"],
            bundleIdentifier: "com.hicka04.Pokedex.Sandbox.PokemonDetail",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "Environment", path: "../Environment"),
        .package(name: "Feature", path: "../Feature")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Routing", package: "Environment"),
                .product(name: "Features", package: "Feature")
            ],
            path: "App"
        ),
        .executableTarget(
            name: "SandboxPokemonListModule",
            dependencies: [
                .product(name: "Routing", package: "Environment"),
                .product(name: "Features", package: "Feature")
            ],
            path: "Sandbox/PokemonList"
        ),
        .executableTarget(
            name: "SandboxPokemonDetailModule",
            dependencies: [
                .product(name: "Routing", package: "Environment"),
                .product(name: "Features", package: "Feature")
            ],
            path: "Sandbox/PokemonDetail"
        )
    ]
)
