// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let dependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Feature", path: "../Feature"),
    .package(name: "Core", path: "../Core")
]

let package = Package(
    name: "Pokedex",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .iOSApplication(
            name: "Pokedex",
            targets: ["AppModule"],
            bundleIdentifier: "dev.hicka04.Pokedex",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
        .iOSApplication(
            name: "PokemonListSandbox",
            targets: ["SandboxPokemonListModule"],
            bundleIdentifier: "dev.hicka04.Pokedex.Sandbox.PokemonList",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
        .iOSApplication(
            name: "PokemonDetailSandbox",
            targets: ["SandboxPokemonDetailModule"],
            bundleIdentifier: "dev.hicka04.Pokedex.Sandbox.PokemonDetail",
            teamIdentifier: "8RYHZQ93KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: dependencies,
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Routing", package: "Core"),
                .product(name: "Features", package: "Feature")
            ],
            path: "App"
        ),
        .executableTarget(
            name: "SandboxPokemonListModule",
            dependencies: [
                .product(name: "Routing", package: "Core"),
                .product(name: "Features", package: "Feature")
            ],
            path: "Sandbox/PokemonList"
        ),
        .executableTarget(
            name: "SandboxPokemonDetailModule",
            dependencies: [
                .product(name: "Routing", package: "Core"),
                .product(name: "Features", package: "Feature")
            ],
            path: "Sandbox/PokemonDetail"
        )
    ]
)
